@startuml

package "Interface / Apresentação" {
  [PedidoController]
}

package "Aplicação" {
  [ConfirmarPedidoService]
}

package "Domínio" {
  [Pedido]
  interface "PedidoRepository" as PedidoRepository
}

package "Infraestrutura" {
  [PedidoRepositoryJpa]
}

PedidoController --> ConfirmarPedidoService : chama
ConfirmarPedidoService --> Pedido : usa
ConfirmarPedidoService --> PedidoRepository : chama
PedidoRepositoryJpa ..|> PedidoRepository : implementa
PedidoRepositoryJpa --> Pedido : persiste

@enduml